---
- name: install HAProxy
  yum:
    name: haproxy 
    state: latest
  
- name: enable HAProxy
  service:
    name: haproxy
    state: started
  
- name: restart HAproxy
  service:
    name: haproxy
    state: restarted
